artifacts_root: Artifacts

data_ingestion:
  root_dir: Artifacts/data_ingestion
  local_data_dir: Artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  local_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  preprocessor_path: final_model/preprocessor.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  model_dir: final_model/model.joblib
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  preprocessor_path: final_model/preprocessor.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: final_model/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

model_prediction:
  root_dir: artifacts/model_prediction
  model_path: final_model/model.joblib
  prediction_file_path: artifacts/model_prediction/prediction.json
